#%RAML 1.0
title: ATM-Api
baseUri: http://localhost:8081/atm
mediaType:
  - application/json

/creatAccount:
  post:
    queryParameters:
      customerName:
        type: string
        maxLength: 45
        minLength: 4
        required: true
      bank:
        type: string
        enum: ["CICI" , "AXIS" ,"HDFC"]
      type:
        required: true
        type: 
        enum: ["current" , "saving"]
      branchName:
        required: true
        type: string
        maxLength: 10
        minLength: 4
    body:
      application/json:
        example: |
          { 
            "accountNum": {
              "required": "true",
              "type": "string",
              "minLength": 10,
              "maxLength": 10,
            }
            "atmPin" : {
              required: true,
              type: string,
              minLength: 4,
              maxLength: 4
            }

          }
        
        
  
   


    

        
          
      
    
    responses:
      201:
        body:
          application/json:
                
/checkBalance:
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/withDraw:
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:


/unblock:
  put:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
                
            
///
          
        
        




    
    
